package br.ufu.facom.mehar.sonar.core.model.configuration;

public enum FlowSelectorType {
	ETH_TYPE, ETH_DST, ETH_SRC,
	IN_PORT, IN_PHY_PORT,
	VLAN_VID, VLAN_PCP, INNER_VLAN_VID, INNER_VLAN_PCP,
	IP_DSCP, IP_ECN, IP_PROTO, IPV4_SRC, IPV4_DST, 
	IPV6_SRC, IPV6_DST, IPV6_FLABEL, IPV6_ND_TARGET, IPV6_ND_SLL, IPV6_ND_TLL, IPV6_EXTHDR,
	ICMPV4_TYPE, ICMPV4_CODE, ICMPV6_TYPE, ICMPV6_CODE, 
	TCP_SRC, TCP_DST, UDP_SRC, UDP_DST, SCTP_SRC, SCTP_DST,
	GRID_TYPE, CHANNEL_SPACING, SPACING_MULIPLIER, SLOT_GRANULARITY,
	MPLS_LABEL, TUNNEL_ID,  
	ODU_SIGTYPE, ODU_SIGID, OCH_SIGID, OCH_SIGTYPE, 
	METADATA; 
}
